development:
  host:                      'localhost'
  host_port:                 3000
  rails_max_threads:         <threads count>
  secret_key_base:           <128 symbols base>
  sandbox_database_username: <username>
  sandbox_database_password: <password>
  time_zone:                 'Kyiv'
  google_app:                <google app id>
  google_secret:             <google secret>

test:
  host:                      'localhost'
  host_port:                 3000
  rails_max_threads:         <threads count>
  secret_key_base:           <128 symbols base>
  sandbox_database_username: <username>
  sandbox_database_password: <password>
  time_zone:                 'Kyiv'
  google_app:                <google app id>
  google_secret:             <google secret>

production:
  host:                      <%= ENV['HOST_URL'] %>
  host_port:                 <%= ENV['HOST_PORT'] %>
  rails_max_threads:         <%= ENV['RAILS_MAX_THREADS'] %>
  secret_key_base:           <%= ENV['SECRET_KEY_BASE'] %>
  sandbox_database_username: <%= ENV['SANDBOX_DATABASE_USERNAME'] %>
  sandbox_database_password: <%= ENV['SANDBOX_DATABASE_PASSWORD'] %>
  time_zone:                 <%= ENV['TIME_ZONE'] %>
  google_app:                <%= ENV['GOOGLE_APP'] %>
  google_secret:             <%= ENV['GOOGLE_SECRET'] %>
  smtp_username:             <%= ENV['SMTP_USERNAME'] %>
  smtp_password:             <%= ENV['SMTP_PASSWORD'] %>
